[container.image]
repository= "cafe-repo" # Container repository to host the container
name="menu" # Name of the container image
tag="1.0.0"  # Tag of the container


[[cloud.config.maps]]
    file="./menus/tea.json" # Path of the external file 
    mount_path="/home/ballerina/menus/tea.json" # Path of the file in the container

[[cloud.config.maps]]
    file="./menus/coffe.json" # Path of the external file 
    mount_path="/home/ballerina/menus/coffe.json" # Path of the file in the container
