[package]
org = "ballerina"
name = "cloud"
version = "@toml.version@"
repository = "https://github.com/ballerina-platform/module-ballerina-c2c"
license = ["Apache-2.0"]
keywords = ["cloud", "kubernetes", "docker", "k8s", "c2c"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true
