[package]
org = "ballerina"
name = "cloud"
version = "2.9.0"
repository = "https://github.com/ballerina-platform/module-ballerina-c2c"
license = ["Apache-2.0"]
keywords = ["cloud", "kubernetes", "docker", "k8s", "c2c"]
distribution = "2201.7.0"
